import Appstore from "./images/Appstore.png"
import Calculator from "./images/Calculator.png"
import calender from "./images/calender.png"
import Camera from "./images/Camera.png"
import Clock from "./images/Clock.png"
import Facetime from "./images/Facetime.png"
import Files from "./images/Files.png"
import GarageBand from "./images/GarageBand.png"
import health from "./images/health.png"
import IMaps from "./images/IMaps.png"
import Instagram from "./images/Instagram.png"
import Lists from "./images/Lists.png"
import Mail from "./images/Mail.png"
import Messages from "./images/Messages.png"
import Music from "./images/Music.png"
import Notes from "./images/Notes.png"
import Phone from "./images/Phone.png"
import Photos from "./images/Photos.png"
import Safari from "./images/Safari.png"
import Settings from "./images/Settings.png"
import Threads from "./images/Threads.png"
import Twitter from "./images/Twitter.png"
import Watsapp from "./images/Watsapp.png"
import Weather from "./images/Weather.png"
import X from "./images/X.png"
import Youtube from "./images/Youtube.png"

export {Appstore,Calculator,calender,Camera,Clock,Facetime,Files,GarageBand,health,IMaps,Instagram,Lists,Mail,Messages,Music,Notes,Phone,Photos,Safari,Settings,Threads,Twitter,Watsapp,Weather,X,Youtube}